server:
  port: 8000

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}/${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #设置与eureka server交互的地址和注册服务都需要依赖这个地址
      defaultZone: http://127.0.0.1:8170/eureka

spring:
  application:
    name: feign-client

#配置feign请求的log
logging:
  level:
    com.csii.service.ExternalApiClient: debug

#配置feign请求的log配置，可以统一默认配置也可以执行feignClient的名字来配置，日志级别有full，basic等
#而日志的级别分为四种：NONE：不记录任何日志信息，这是默认值。 BASIC：仅记录请求的方法，URL以及响应状态码和执行时间
#HEADERS：在BASIC的基础上，额外记录了请求和响应的头信息 FULL：记录所有请求和响应的明细，包括头信息、请求体、元数据。
#参考文章：https://cloud.tencent.com/developer/article/2153158
#https://blog.csdn.net/qi341500/article/details/129300783
feign:
  client:
    config:
      default:   # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      externalApi:  #针对某个微服务的配置
        loggerLevel: full

